#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import {
  type ExportFormat,
  type ExternalImageAssetSpec,
  type GeneratedImageAssetSpec,
  type InspectQuery,
  type RetrievedImageAssetSpec,
  buildPresentationIr,
  createLocalRuntime,
  createPresentationSpec,
  generateAssetPlan,
  generateDeckPlan,
  generateImageFromAssetSpec,
  generateSlideSpecs,
  inspectPresentation,
  loadPresentationFromFile,
  retrieveImageFromAssetSpec,
  searchImageCandidates,
  validatePresentation,
} from "@deck-forge/core";

export type CliIO = {
  stdout: (text: string) => void;
  stderr: (text: string) => void;
};

export async function runCli(argv: string[], io: CliIO = defaultIO): Promise<number> {
  const [command, ...rest] = argv;

  if (!command || command === "help" || command === "--help" || command === "-h") {
    io.stdout(helpText());
    return 0;
  }

  if (command === "inspect") {
    return runInspect(rest, io);
  }

  if (command === "init") {
    return runInit(rest, io);
  }

  if (command === "plan") {
    return runPlan(rest, io);
  }

  if (command === "build") {
    return runBuild(rest, io);
  }

  if (command === "generate-image") {
    return runGenerateImage(rest, io);
  }

  if (command === "search-assets") {
    return runSearchAssets(rest, io);
  }

  if (command === "fetch-asset") {
    return runFetchAsset(rest, io);
  }

  if (command === "validate") {
    return runValidate(rest, io);
  }

  if (command === "export") {
    return runExport(rest, io);
  }

  io.stderr(`Unknown command: ${command}`);
  io.stdout(helpText());
  return 1;
}

async function runInspect(args: string[], io: CliIO): Promise<number> {
  const inputPath = args[0];

  if (!inputPath) {
    io.stderr("inspect requires an input JSON path.");
    return 1;
  }

  const out = getOptionValue(args.slice(1), ["--out", "--output"]);
  const slideId = getOptionValue(args.slice(1), ["--slide"]);
  const elementId = getOptionValue(args.slice(1), ["--element"]);
  const targetId = getOptionValue(args.slice(1), ["--target"]);
  const includeRaw = getOptionValue(args.slice(1), ["--include"]);
  const include = includeRaw
    ? includeRaw
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean)
    : undefined;

  const presentation = await loadPresentationFromFile(inputPath);
  const query: InspectQuery = {
    include: include as InspectQuery["include"],
    slideId,
    elementId,
    targetId,
  };

  const result = await inspectPresentation(presentation, query);
  const payload = JSON.stringify(result, null, 2);

  if (out) {
    await writeFile(out, payload, "utf8");
    io.stdout(`wrote inspect result: ${out}`);
    return 0;
  }

  io.stdout(payload);
  return 0;
}

async function runPlan(args: string[], io: CliIO): Promise<number> {
  const requestText = args[0];
  if (!requestText) {
    io.stderr("plan requires a user request text.");
    return 1;
  }

  const out = getOptionValue(args.slice(1), ["--out", "--output"]);
  const audience = getOptionValue(args.slice(1), ["--audience"]);
  const goal = getOptionValue(args.slice(1), ["--goal"]);
  const tone = getOptionValue(args.slice(1), ["--tone"]);
  const slideCountRaw = getOptionValue(args.slice(1), ["--slide-count"]);
  const slideCount = slideCountRaw ? Number(slideCountRaw) : undefined;
  const outputFormat = getOptionValue(args.slice(1), ["--format", "--output-format"]);

  const { brief } = await createPresentationSpec({
    userRequest: requestText,
    audience,
    goal,
    tone,
    slideCount: Number.isFinite(slideCount) ? slideCount : undefined,
    outputFormat:
      outputFormat === "pptx" ||
      outputFormat === "pdf" ||
      outputFormat === "html" ||
      outputFormat === "json"
        ? outputFormat
        : undefined,
  });
  const { deckPlan } = await generateDeckPlan({ brief });

  const payload = JSON.stringify({ brief, deckPlan }, null, 2);
  if (out) {
    await writeFile(out, payload, "utf8");
    io.stdout(`wrote plan output: ${out}`);
    return 0;
  }

  io.stdout(payload);
  return 0;
}

async function runBuild(args: string[], io: CliIO): Promise<number> {
  const inputPath = args[0];
  if (!inputPath) {
    io.stderr("build requires an input JSON path generated by plan.");
    return 1;
  }

  const extraArgs = args.slice(1);
  const out = getOptionValue(extraArgs, ["--out", "--output"]);
  const planPath = getOptionValue(extraArgs, ["--plan"]);
  const presentationOut = getOptionValue(extraArgs, ["--presentation-out", "--presentation"]);
  const acquisitionModeValue = getOptionValue(extraArgs, ["--asset-mode"]);
  const acquisitionMode: AssetAcquisitionMode | undefined =
    acquisitionModeValue === "generate" ||
    acquisitionModeValue === "retrieve" ||
    acquisitionModeValue === "auto"
      ? acquisitionModeValue
      : undefined;

  const inputPayload = await readJsonFromFile<BuildInputPayload>(inputPath);

  const planPayload = planPath ? await readJsonFromFile<PlanPayload>(planPath) : undefined;
  const brief = inputPayload.brief ?? planPayload?.brief;
  const deckPlan = inputPayload.deckPlan ?? planPayload?.deckPlan;

  const buildResult = await resolveBuildResult(inputPayload, brief, deckPlan, acquisitionMode);

  if (!buildResult) {
    io.stderr(
      "build input must include brief/deckPlan (plan output) or slideSpecs/assetSpecs (build output).",
    );
    return 1;
  }

  const result = JSON.stringify(
    {
      slideSpecs: buildResult.slideSpecs,
      assetSpecs: buildResult.assetSpecs,
    },
    null,
    2,
  );

  if (out) {
    await writeFile(out, result, "utf8");
    io.stdout(`wrote build output: ${out}`);
  } else {
    io.stdout(result);
  }

  if (presentationOut) {
    if (!brief || !deckPlan) {
      io.stderr(
        "presentation artifact requires brief and deckPlan. Pass --plan when using build.json.",
      );
      return 1;
    }

    const presentation = createPresentationArtifact({
      brief,
      deckPlan,
      slideSpecs: buildResult.slideSpecs,
      assetSpecs: buildResult.assetSpecs,
    });
    await writeFile(presentationOut, JSON.stringify(presentation, null, 2), "utf8");
    io.stdout(`wrote presentation artifact: ${presentationOut}`);
  }

  return 0;
}

async function runValidate(args: string[], io: CliIO): Promise<number> {
  const inputPath = args[0];

  if (!inputPath) {
    io.stderr("validate requires an input JSON path.");
    return 1;
  }

  const out = getOptionValue(args.slice(1), ["--out", "--output"]);
  const level = getOptionValue(args.slice(1), ["--level"]);
  const presentation = await loadPresentationFromFile(inputPath);
  const report = await validatePresentation(presentation, {
    level: level === "strict" || level === "export" ? level : "basic",
  });
  const payload = JSON.stringify(report, null, 2);

  if (out) {
    await writeFile(out, payload, "utf8");
    io.stdout(`wrote validation report: ${out}`);
    return report.status === "failed" ? 2 : 0;
  }

  io.stdout(payload);
  return report.status === "failed" ? 2 : 0;
}

async function runGenerateImage(args: string[], io: CliIO): Promise<number> {
  const assetSpecPath = args[0];
  if (!assetSpecPath) {
    io.stderr("generate-image requires an asset spec JSON path.");
    return 1;
  }

  const extraArgs = args.slice(1);
  const out = getOptionValue(extraArgs, ["--out", "--output"]);
  const outputDir = getOptionValue(extraArgs, ["--output-dir"]);
  const workspaceRoot = getOptionValue(extraArgs, ["--workspace-root"]) ?? process.cwd();
  const allowOutsideWorkspace = getFlag(extraArgs, "--allow-outside-workspace");
  const presentationPath = getOptionValue(extraArgs, ["--presentation"]);
  const presentationOut = getOptionValue(extraArgs, ["--presentation-out"]) ?? presentationPath;
  const preferredGenerator = getOptionValue(extraArgs, ["--generator", "--preferred-generator"]);
  const provider = getOptionValue(extraArgs, ["--provider"]);
  const model = getOptionValue(extraArgs, ["--model"]);
  const timeoutMsRaw = getOptionValue(extraArgs, ["--timeout-ms"]);
  const retriesRaw = getOptionValue(extraArgs, ["--retries"]);
  const openaiApiKey = getOptionValue(extraArgs, ["--openai-api-key"]);
  const openaiBaseUrl = getOptionValue(extraArgs, ["--openai-base-url"]);
  const bedrockRegion = getOptionValue(extraArgs, ["--bedrock-region"]);
  const bedrockModelId = getOptionValue(extraArgs, ["--bedrock-model-id"]);
  const timeoutMs = timeoutMsRaw ? Number(timeoutMsRaw) : undefined;
  const retries = retriesRaw ? Number(retriesRaw) : undefined;

  const assetSpec = await readJsonFromFile<GeneratedImageAssetSpec>(assetSpecPath);
  const asset = await generateImageFromAssetSpec(assetSpec, {
    outputDir,
    preferredGenerator: preferredGenerator ?? undefined,
    provider:
      provider === "openai" || provider === "bedrock" || provider === "local-file"
        ? provider
        : undefined,
    model: model ?? undefined,
    timeoutMs: Number.isFinite(timeoutMs) && (timeoutMs ?? 0) > 0 ? timeoutMs : undefined,
    retries: Number.isFinite(retries) && (retries ?? -1) >= 0 ? retries : undefined,
    openaiApiKey: openaiApiKey ?? undefined,
    openaiBaseUrl: openaiBaseUrl ?? undefined,
    bedrockRegion: bedrockRegion ?? undefined,
    bedrockModelId: bedrockModelId ?? undefined,
    fallbackPolicy: "local-file",
    safety: {
      workspaceRoot,
      allowOutsideWorkspace,
    },
  });

  if (presentationPath) {
    const presentation = await loadPresentationFromFile(presentationPath);
    const nextAssets = [...presentation.assets.assets];
    const existingIndex = nextAssets.findIndex((item) => item.id === asset.id);

    if (existingIndex >= 0) {
      const existing = nextAssets[existingIndex];
      nextAssets[existingIndex] = {
        ...asset,
        usage: existing?.usage ?? asset.usage,
        specId: existing?.specId ?? asset.specId,
      };
    } else {
      nextAssets.push(asset);
    }

    if (!presentationOut) {
      io.stderr(
        "generate-image with --presentation requires writable path via --presentation-out or same --presentation path.",
      );
      return 1;
    }

    await writeFile(
      presentationOut,
      JSON.stringify(
        {
          ...presentation,
          assets: {
            assets: nextAssets,
          },
        },
        null,
        2,
      ),
      "utf8",
    );
    io.stdout(`wrote updated presentation: ${presentationOut}`);
  }

  const payload = JSON.stringify({ asset }, null, 2);
  if (out) {
    await writeFile(out, payload, "utf8");
    io.stdout(`wrote generated asset: ${out}`);
    return 0;
  }

  io.stdout(payload);
  return 0;
}

async function runSearchAssets(args: string[], io: CliIO): Promise<number> {
  const query = args[0];
  if (!query) {
    io.stderr("search-assets requires a query text.");
    return 1;
  }

  const provider = getOptionValue(args.slice(1), ["--provider"]);
  const limitRaw = getOptionValue(args.slice(1), ["--limit"]);
  const unsplashApiKey = getOptionValue(args.slice(1), ["--unsplash-api-key"]);
  const pexelsApiKey = getOptionValue(args.slice(1), ["--pexels-api-key"]);
  const pixabayApiKey = getOptionValue(args.slice(1), ["--pixabay-api-key"]);
  const limit = limitRaw ? Number(limitRaw) : undefined;

  try {
    const candidates = await searchImageCandidates(query, {
      provider:
        provider === "unsplash" || provider === "pexels" || provider === "pixabay"
          ? provider
          : undefined,
      limit: Number.isFinite(limit) && (limit ?? 0) > 0 ? limit : undefined,
      unsplashApiKey: unsplashApiKey ?? undefined,
      pexelsApiKey: pexelsApiKey ?? undefined,
      pixabayApiKey: pixabayApiKey ?? undefined,
    });

    io.stdout(JSON.stringify({ candidates }, null, 2));
    return 0;
  } catch (error) {
    io.stderr(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

async function runFetchAsset(args: string[], io: CliIO): Promise<number> {
  const assetSpecPath = args[0];
  if (!assetSpecPath) {
    io.stderr("fetch-asset requires an asset spec JSON path.");
    return 1;
  }

  const extraArgs = args.slice(1);
  const outputDir = getOptionValue(extraArgs, ["--output-dir"]);
  const workspaceRoot = getOptionValue(extraArgs, ["--workspace-root"]) ?? process.cwd();
  const allowOutsideWorkspace = getFlag(extraArgs, "--allow-outside-workspace");
  const out = getOptionValue(extraArgs, ["--out", "--output"]);
  const unsplashApiKey = getOptionValue(extraArgs, ["--unsplash-api-key"]);
  const pexelsApiKey = getOptionValue(extraArgs, ["--pexels-api-key"]);
  const pixabayApiKey = getOptionValue(extraArgs, ["--pixabay-api-key"]);

  try {
    const assetSpec = await readJsonFromFile<RetrievedImageAssetSpec | ExternalImageAssetSpec>(
      assetSpecPath,
    );
    const asset = await retrieveImageFromAssetSpec(assetSpec, {
      outputDir,
      safety: {
        workspaceRoot,
        allowOutsideWorkspace,
      },
      unsplashApiKey: unsplashApiKey ?? undefined,
      pexelsApiKey: pexelsApiKey ?? undefined,
      pixabayApiKey: pixabayApiKey ?? undefined,
    });

    const payload = JSON.stringify({ asset }, null, 2);
    if (out) {
      await writeFile(out, payload, "utf8");
      io.stdout(`wrote retrieved asset: ${out}`);
      return 0;
    }

    io.stdout(payload);
    return 0;
  } catch (error) {
    io.stderr(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

async function runExport(args: string[], io: CliIO): Promise<number> {
  const inputPath = args[0];

  if (!inputPath) {
    io.stderr("export requires an input JSON path.");
    return 1;
  }

  const format = getOptionValue(args.slice(1), ["--format"]) as ExportFormat | undefined;
  const out = getOptionValue(args.slice(1), ["--out", "--output"]);
  const workspaceRoot = getOptionValue(args.slice(1), ["--workspace-root"]) ?? process.cwd();
  const allowOutsideWorkspace = getFlag(args.slice(1), "--allow-outside-workspace");

  if (!format) {
    io.stderr("export requires --format <json|pptx|html|pdf>.");
    return 1;
  }

  if (format !== "json" && format !== "pptx" && format !== "html" && format !== "pdf") {
    io.stderr(`Unsupported export format: ${format}. Supported: json, pptx, html, pdf`);
    return 1;
  }

  if ((format === "pptx" || format === "html" || format === "pdf") && !out) {
    io.stderr(`${format} export requires --out <path>.`);
    return 1;
  }

  const presentation = await loadPresentationFromFile(inputPath);
  const runtime = createLocalRuntime({
    safety: {
      workspaceRoot,
      allowOutsideWorkspace,
    },
  });
  const result = await runtime.export(presentation, {
    format,
    outputPath: out,
  });

  if (typeof result.data === "string") {
    io.stdout(result.data);
    return 0;
  }

  io.stdout(
    JSON.stringify(
      {
        format: result.format,
        path: result.path,
        warnings: result.warnings,
      },
      null,
      2,
    ),
  );

  return 0;
}

type BuildPresentationInput = Parameters<typeof buildPresentationIr>[0];

async function runInit(args: string[], io: CliIO): Promise<number> {
  const out = args[0] ?? getOptionValue(args, ["--out", "--output"]) ?? "presentation.json";

  const skeleton = {
    id: "presentation-001",
    version: "1.0.0",
    meta: {
      title: "My Presentation",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    theme: {
      id: "default",
      name: "Default",
      colors: {
        background: "#FFFFFF",
        surface: "#F8FAFC",
        textPrimary: "#0F172A",
        textSecondary: "#64748B",
        primary: "#3B82F6",
        secondary: "#8B5CF6",
        accent: "#F59E0B",
        chartPalette: ["#3B82F6", "#8B5CF6", "#F59E0B", "#10B981", "#EF4444"],
      },
      typography: {
        fontFamily: { heading: "Calibri", body: "Calibri" },
        fontSize: { title: 36, heading: 28, body: 18, caption: 14, footnote: 12 },
        lineHeight: { tight: 1.2, normal: 1.5, relaxed: 1.8 },
        weight: { regular: 400, medium: 500, bold: 700 },
      },
      spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 40, xxl: 64 },
      radius: { sm: 4, md: 8, lg: 16, full: 9999 },
      slideDefaults: { backgroundColor: "#FFFFFF", padding: 80 },
      elementDefaults: {
        text: {
          fontFamily: "Calibri",
          fontSize: 18,
          color: "#0F172A",
          bold: false,
          italic: false,
          underline: false,
        },
      },
    },
    slides: [],
    assets: { assets: [] },
    operationLog: [],
  };

  await writeFile(out, JSON.stringify(skeleton, null, 2), "utf8");
  io.stdout(`Created ${out}`);
  return 0;
}
type PlanPayload = Partial<Pick<BuildPresentationInput, "brief" | "deckPlan">>;
type BuildPayload = Partial<
  Pick<BuildPresentationInput, "brief" | "deckPlan" | "slideSpecs" | "assetSpecs">
>;
type BuildInputPayload = PlanPayload | BuildPayload;
type BuildResultPayload = Pick<BuildPresentationInput, "slideSpecs" | "assetSpecs">;
type AssetAcquisitionMode = "generate" | "retrieve" | "auto";

async function readJsonFromFile<T>(path: string): Promise<T> {
  const payloadRaw = await readFile(path, "utf8");
  return JSON.parse(payloadRaw) as T;
}

async function resolveBuildResult(
  payload: BuildInputPayload,
  brief: BuildPresentationInput["brief"] | undefined,
  deckPlan: BuildPresentationInput["deckPlan"] | undefined,
  acquisitionMode?: AssetAcquisitionMode,
): Promise<BuildResultPayload | null> {
  if (
    Array.isArray((payload as BuildPayload).slideSpecs) &&
    Array.isArray((payload as BuildPayload).assetSpecs)
  ) {
    return {
      slideSpecs: (payload as BuildPayload).slideSpecs ?? [],
      assetSpecs: (payload as BuildPayload).assetSpecs ?? [],
    };
  }

  if (!brief || !deckPlan) {
    return null;
  }

  const { slideSpecs } = await generateSlideSpecs({
    brief,
    deckPlan,
  });
  const { assetSpecs } = await generateAssetPlan({
    brief,
    slideSpecs,
    acquisitionMode,
  });

  return { slideSpecs, assetSpecs };
}

function createPresentationArtifact(input: {
  brief: BuildPresentationInput["brief"];
  deckPlan: BuildPresentationInput["deckPlan"];
  slideSpecs: BuildPresentationInput["slideSpecs"];
  assetSpecs: BuildPresentationInput["assetSpecs"];
}) {
  return buildPresentationIr({
    brief: input.brief,
    deckPlan: input.deckPlan,
    slideSpecs: input.slideSpecs,
    assetSpecs: input.assetSpecs,
  });
}

function getOptionValue(args: string[], names: string[]): string | undefined {
  for (let i = 0; i < args.length; i += 1) {
    const current = args[i];
    if (!current || !names.includes(current)) {
      continue;
    }

    const next = args[i + 1];
    if (!next || next.startsWith("-")) {
      return undefined;
    }

    return next;
  }

  return undefined;
}

function getFlag(args: string[], name: string): boolean {
  return args.includes(name);
}

function helpText(): string {
  return [
    "deck-forge <command>",
    "",
    "Commands:",
    "  init [presentation.json] [--out <path>]",
    "  plan <request> [--audience <text>] [--goal <text>] [--tone <text>] [--slide-count <n>] [--format <pptx|pdf|html|json>] [--out <path>]",
    "  build <plan.json|build.json> [--plan <plan.json>] [--asset-mode <generate|retrieve|auto>] [--out <path>] [--presentation-out <path>]",
    "  search-assets <query> [--provider <unsplash|pexels|pixabay>] [--limit <n>] [--unsplash-api-key <key>] [--pexels-api-key <key>] [--pixabay-api-key <key>]",
    "  fetch-asset <asset-spec.json> [--output-dir <dir>] [--unsplash-api-key <key>] [--pexels-api-key <key>] [--pixabay-api-key <key>] [--workspace-root <path>] [--allow-outside-workspace] [--out <asset.json>]",
    "  generate-image <asset-spec.json> [--output-dir <dir>] [--provider <openai|bedrock|local-file>] [--model <id>] [--timeout-ms <n>] [--retries <n>] [--openai-api-key <key>] [--openai-base-url <url>] [--bedrock-region <region>] [--bedrock-model-id <id>] [--workspace-root <path>] [--allow-outside-workspace] [--generator <name>] [--presentation <presentation.json>] [--presentation-out <path>] [--out <asset.json>]",
    "  inspect <presentation.json> [--slide <id>] [--element <id>] [--target <anchor>] [--include a,b,c] [--out <path>]",
    "  validate <presentation.json> [--level <basic|strict|export>] [--out <path>]",
    "  export <presentation.json> --format <json|pptx|html|pdf> [--out <path>] [--workspace-root <path>] [--allow-outside-workspace]",
  ].join("\n");
}

const defaultIO: CliIO = {
  stdout: (text) => {
    process.stdout.write(`${text}\n`);
  },
  stderr: (text) => {
    process.stderr.write(`${text}\n`);
  },
};

if (isMainModule()) {
  runCli(process.argv.slice(2)).then((code) => {
    process.exitCode = code;
  });
}

function isMainModule(): boolean {
  const entry = process.argv[1];
  if (!entry) {
    return false;
  }

  return fileURLToPath(import.meta.url) === entry;
}
